image:
  repository: 141571819416.dkr.ecr.ap-southeast-1.amazonaws.com/banking-microservices-staging-account-service
  tag: "0fd80aa0a6549a11015fb3fd05ff7c790f2d2fd9"

replicaCount: 1

container:
  port: 8084

service:
  port: 8084
  targetPort: http

ingress:
  enabled: false
  className: nginx
  annotations: {}
  hosts:
    - host: account.staging.banking.local
      paths:
        - path: /
          pathType: Prefix

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi
