image:
  repository: 141571819416.dkr.ecr.ap-southeast-1.amazonaws.com/banking-microservices-staging-account-service
  tag: "adbb96125ae94d5d078fac10e5b86ceee6f956f7"

replicaCount: 1

container:
  port: 8084

service:
  port: 8084
  targetPort: http

ingress:
  enabled: false
  className: nginx
  annotations: {}
  hosts:
    - host: account.staging.banking.local
      paths:
        - path: /
          pathType: Prefix

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 4
  targetCPUUtilizationPercentage: 80
