image:
  repository: 141571819416.dkr.ecr.ap-southeast-1.amazonaws.com/banking-microservices-staging-credit-card-service
  tag: "381820afbdd92f52f2aef56c10342685f0cf19db"

replicaCount: 1

container:
  port: 8083

extraEnv:
  - name: USER_SERVICE_HOST
    value: user-staging-banking-spring-boot
  - name: BANK_SERVICE_HOST
    value: bank-staging-banking-spring-boot

service:
  port: 8083
  targetPort: http

ingress:
  enabled: false
  className: nginx
  annotations: {}
  hosts:
    - host: creditcard.staging.banking.local
      paths:
        - path: /
          pathType: Prefix

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

probes:
  liveness:
    enabled: true
    spec:
      httpGet:
        path: /actuator/health/liveness
        port: http
      initialDelaySeconds: 180
      periodSeconds: 15
      timeoutSeconds: 5
      failureThreshold: 3
  readiness:
    enabled: true
    spec:
      httpGet:
        path: /actuator/health/readiness
        port: http
      initialDelaySeconds: 180
      periodSeconds: 10
      timeoutSeconds: 5
      failureThreshold: 3
  startup:
    enabled: true
    spec:
      httpGet:
        path: /actuator/health
        port: http
      initialDelaySeconds: 30
      periodSeconds: 10
      timeoutSeconds: 5
      failureThreshold: 24
