image:
  repository: banking-microservices-staging-discovery-client-service
  tag: "73f7b3d93bd2d3a0c54c5b9304f042072d960918"

replicaCount: 1

container:
  port: 8761

service:
  port: 8761
  targetPort: http

ingress:
  enabled: true
  className: nginx
  annotations: {}
  hosts:
    - host: discovery.staging.banking.local
      paths:
        - path: /
          pathType: Prefix

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

probes:
  liveness:
    enabled: true
    spec:
      httpGet:
        path: /actuator/health/liveness
        port: http
      initialDelaySeconds: 90
      periodSeconds: 15
      timeoutSeconds: 5
      failureThreshold: 10
  readiness:
    enabled: true
    spec:
      httpGet:
        path: /actuator/health/readiness
        port: http
      initialDelaySeconds: 45
      periodSeconds: 10
      timeoutSeconds: 5
      failureThreshold: 12
  startup:
    enabled: true
    spec:
      httpGet:
        path: /actuator/health
        port: http
      initialDelaySeconds: 20
      periodSeconds: 10
      timeoutSeconds: 5
      failureThreshold: 30
