image:
  repository: banking-microservices-staging-api-gateway-service
  tag: "e5c42ed238a9a37a735f0fad0975fa9cd5b351ba"

replicaCount: 1

container:
  port: 8087

service:
  port: 8087
  targetPort: http

ingress:
  enabled: true
  className: nginx
  annotations: {}
  hosts:
    - host: gateway.staging.banking.local
      paths:
        - path: /
          pathType: Prefix

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi
