image:
  repository: banking-microservices-staging-api-gateway-service
  tag: "3f661fd295bdf8be46f84d26b9c16ee8fe87e1e4"

replicaCount: 1

container:
  port: 8087

service:
  port: 8087
  targetPort: http

ingress:
  enabled: true
  className: "alb"
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}]'
  hosts:
    - host: gateway.staging.banking.local
      paths:
        - path: /
          pathType: Prefix

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi
