postgres:
  enabled: false
rabbitmq:
  enabled: true
  image:
    repository: bitnamilegacy/rabbitmq
    tag: 3.13.2-debian-12-r0
  persistence:
    storageClass: gp2
mongodb:
  enabled: false
  image:
    repository: bitnamilegacy/mongodb
redis:
  enabled: false
  image:
    repository: bitnamilegacy/redis

global:
  security:
    allowInsecureImages: true

postgresql:
  image:
    repository: bitnamilegacy/postgresql

externalServices:
  postgres:
    enabled: true
    host: ""
    port: 5432
    database: "banking"
    hostSecretRef:
      name: "staging-rds-credentials"
      key: "host"
  rabbitmq:
    enabled: false
    host: ""
    port: 5672
  mongodb:
    enabled: true
    uri: ""
    hostSecretRef:
      name: "staging-docdb-credentials"
      key: "host"
  redis:
    enabled: true
    host: ""
    port: 6379
    hostSecretRef:
      name: "staging-elasticache-credentials"
      key: "host"
