postgres:
  enabled: false
rabbitmq:
  enabled: true
  image:
    repository: bitnamilegacy/rabbitmq
    tag: 3.13.2-debian-12-r0
mongodb:
  enabled: false
  image:
    repository: bitnamilegacy/mongodb
redis:
  enabled: false
  image:
    repository: bitnamilegacy/redis

global:
  security:
    allowInsecureImages: true

postgresql:
  image:
    repository: bitnamilegacy/postgresql

externalServices:
  postgres:
    enabled: true
    host: "TF_STAGING_RDS_HOST"
    port: 5432
    database: "banking"
  rabbitmq:
    enabled: false
    host: ""
    port: 5672
  mongodb:
    enabled: true
    uri: "mongodb://TF_STAGING_DOCDB_HOST:27017/banking"
  redis:
    enabled: true
    host: "TF_STAGING_ELASTICACHE_HOST"
    port: 6379
