image:
  repository: 141571819416.dkr.ecr.ap-southeast-1.amazonaws.com/banking-microservices-staging-user-service
  tag: "26da0ae5e1ddd26b0a5325f1de45ecae25f0e13b"

replicaCount: 1

container:
  port: 8081
dependencies:
  postgres:
    enabled: true
    host: ""
    port: 5432
    database: ""
    databaseSecretRef:
      name: "staging-rds-credentials"
      key: "dbname"
    username: "bankingadmin"
    hostSecretRef:
      name: "staging-rds-credentials"
      key: "host"
    passwordSecret:
      name: "staging-rds-credentials"
      key: "password"
  rabbitmq:
    enabled: true
    host: "infra-staging-rabbitmq.banking-infra.svc.cluster.local"
    port: 5672
    username: "user"
    passwordSecret:
      name: "infra-staging-rabbitmq"
      key: "rabbitmq-password"
  redis:
    enabled: true
    host: ""
    port: 6379
    database: 1
    hostSecretRef:
      name: "staging-elasticache-credentials"
      key: "host"
    passwordSecret:
      name: "staging-elasticache-credentials"
      key: "auth_token"
  env:
    - name: EUREKA_SERVER_URL
      value: http://172.20.105.215:8761/eureka
    - name: EUREKA_HOST
      value: "172.20.105.215"
    - name: EUREKA_PORT
      value: "8761"

service:
  port: 8081
  targetPort: http

ingress:
  enabled: false
  className: nginx
  annotations: {}
  hosts:
    - host: user.staging.banking.local
      paths:
        - path: /
          pathType: Prefix

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

probes:
  liveness:
    enabled: true
    spec:
      httpGet:
        path: /actuator/health/liveness
        port: http
      initialDelaySeconds: 180
      periodSeconds: 15
      timeoutSeconds: 5
      failureThreshold: 3
  readiness:
    enabled: true
    spec:
      httpGet:
        path: /actuator/health/readiness
        port: http
      initialDelaySeconds: 180
      periodSeconds: 10
      timeoutSeconds: 5
      failureThreshold: 3
  startup:
    enabled: true
    spec:
      httpGet:
        path: /actuator/health
        port: http
      initialDelaySeconds: 30
      periodSeconds: 10
      timeoutSeconds: 5
      failureThreshold: 24
