apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: banking-prod-core-shared-secrets
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
    platform.banking.io/layer: core
    platform.banking.io/priority: foundational
spec:
  project: banking-prod
  destination:
    server: https://kubernetes.default.svc
    namespace: banking-prod
  source:
    repoURL: https://github.com/LeDangQuocAn/banking-gitops.git
    targetRevision: production
    path: charts/shared-secrets
    helm:
      releaseName: shared-secrets-prod
      valueFiles:
        - ../../environments/prod/shared-secrets-values.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
