image:
  repository: 141571819416.dkr.ecr.ap-southeast-1.amazonaws.com/banking-microservices-prod-bank-service
  tag: "d3b1e8674d560e3d0146dfa500930045f193904e"

replicaCount: 2

container:
  port: 8083

service:
  port: 8083
  targetPort: http

ingress:
  enabled: false
  className: "alb"
  annotations: {}
  hosts:
    - host: ""
      paths:
        - path: /
          pathType: Prefix

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi
