image:
  repository: 141571819416.dkr.ecr.ap-southeast-1.amazonaws.com/banking-microservices-prod-credit-card-service
  tag: "a2075de114c47fd5d715876fab6a65898604ef9d"

replicaCount: 2

container:
  port: 8085

service:
  port: 8085
  targetPort: http

ingress:
  enabled: false
  className: "alb"
  annotations: {}
  hosts:
    - host: ""
      paths:
        - path: /
          pathType: Prefix

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi
