image:
  repository: 141571819416.dkr.ecr.ap-southeast-1.amazonaws.com/banking-microservices-prod-discovery-client-service
  tag: "968d9bfc7fc346a7a94e06eda5f4ce48024fceca"

replicaCount: 2

container:
  port: 8761

service:
  port: 8761
  targetPort: http

ingress:
  enabled: false
  className: "alb"
  annotations: {}
  hosts:
    - host: ""
      paths:
        - path: /
          pathType: Prefix

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi
