image:
  repository: 141571819416.dkr.ecr.ap-southeast-1.amazonaws.com/banking-microservices-prod-api-gateway-service
  tag: "d3b1e8674d560e3d0146dfa500930045f193904e"

replicaCount: 2

container:
  port: 8087

service:
  port: 8087
  targetPort: http

ingress:
  enabled: true
  className: "alb"
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}]'
  hosts:
    - host: ""
      paths:
        - path: /
          pathType: Prefix

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi
