postgres:
  enabled: false
rabbitmq:
  enabled: false
  image:
    repository: bitnamilegacy/rabbitmq
    tag: 3.13.2-debian-12-r0
mongodb:
  enabled: false
  image:
    repository: bitnamilegacy/mongodb
redis:
  enabled: false
  image:
    repository: bitnamilegacy/redis

global:
  security:
    allowInsecureImages: true

postgresql:
  image:
    repository: bitnamilegacy/postgresql

externalServices:
  postgres:
    enabled: true
    host: "prod-rds.endpoint.amazonaws.com"
    port: 5432
    database: "banking"
  rabbitmq:
    enabled: true
    host: "prod-rabbitmq.endpoint.amazonaws.com"
    port: 5672
  mongodb:
    enabled: true
    uri: "mongodb://prod-docdb.endpoint.amazonaws.com:27017/banking"
  redis:
    enabled: true
    host: "prod-elasticache.endpoint.amazonaws.com"
    port: 6379
