postgres:
  enabled: false

rabbitmq:
  enabled: false
  image:
    repository: bitnamilegacy/rabbitmq
    tag: 3.13.2-debian-12-r0

mongodb:
  enabled: false
  image:
    repository: bitnamilegacy/mongodb

redis:
  enabled: false
  image:
    repository: bitnamilegacy/redis

global:
  security:
    allowInsecureImages: true

postgresql:
  image:
    repository: bitnamilegacy/postgresql

externalServices:
  postgres:
    enabled: true
    host: ""
    port: 5432
    database: banking
  rabbitmq:
    enabled: true
    host: ""
    port: 5671
  mongodb:
    enabled: true
    uri: ""
  redis:
    enabled: true
    host: ""
    port: 6379
