alertmanager:
  enabled: true
  config:
    global:
      resolve_timeout: 5m
    route:
      group_by: ['namespace', 'alertname']
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 12h
      receiver: 'slack-notifications'
      routes:
        - receiver: 'slack-notifications'
          matchers:
            - severity="critical"
    receivers:
      - name: 'slack-notifications'
        slack_configs:
          - api_url_file: "/etc/alertmanager/secrets/prod-slack-webhook/url"
            send_resolved: true
            title: '[{{ .Status | toUpper }}] {{ .GroupLabels.alertname }}'
            text: >-
              {{ range .Alerts }}
                *Alert:* {{ .Annotations.summary }}
                *Description:* {{ .Annotations.description }}
                *Severity:* `{{ .Labels.severity }}`
                *Started:* {{ .StartsAt }}
              {{ end }}

  alertmanagerSpec:
    replicas: 2
    secrets:
      - prod-slack-webhook
    storage:
      volumeClaimTemplate:
        spec:
          storageClassName: gp3
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 5Gi

prometheus:
  prometheusSpec:
    replicas: 2
    retention: 15d
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: gp3
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 30Gi

grafana:
  persistence:
    enabled: true
    storageClassName: gp3
    accessModes:
      - ReadWriteOnce
    size: 10Gi

  defaultDatasourceEnabled: true

  sidecar:
    dashboards:
      enabled: true
      label: grafana_dashboard
      labelValue: "1"
    datasources:
      enabled: true
      uid: "prometheus"
      alertmanager:
        enabled: false

  additionalDataSources:
    - name: Loki
      type: loki
      uid: loki
      url: http://loki-stack.monitoring.svc.cluster.local:3100
      access: proxy
      isDefault: false
