namespace: banking-prod

clusterSecretStore:
  enabled: true
  name: aws-secrets-manager-prod
  provider: aws
  aws:
    region: ap-southeast-1
    auth:
      serviceAccountRef:
        name: external-secrets
        namespace: external-secrets

externalSecrets:
  secretStore:
    name: aws-secrets-manager-prod
    kind: ClusterSecretStore
  refreshInterval: 1h

  rdsCredentials:
    enabled: true
    name: prod-rds-external-secret
    targetName: banking-prod-rds-secret
    vaultPath: Banking-Microservices-Prod-rds-credentials

  elasticacheCredentials:
    enabled: true
    name: prod-redis-external-secret
    targetName: banking-prod-redis-secret
    vaultPath: Banking-Microservices-Prod-redis-auth-token

  docdbCredentials:
    enabled: true
    name: prod-docdb-external-secret
    targetName: banking-prod-docdb-secret
    vaultPath: Banking-Microservices-Prod-docdb-credentials

  rabbitmqCredentials:
    enabled: false
    name: prod-rabbitmq-external-secret
    targetName: banking-prod-rabbitmq-secret
    vaultPath: banking/rabbitmq

  mqCredentials:
    enabled: true
    name: prod-mq-external-secret
    targetName: banking-prod-mq-secret
    targetNamespace: banking-prod
    secretName: Banking-Microservices-Prod-amazon-mq-credentials

  slackWebhook:
    enabled: true
    name: prod-slack-webhook-external-secret
    targetName: prod-slack-webhook
    targetNamespace: monitoring
    vaultPath: Banking-Microservices-Prod-slack-webhook
