apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: staging-edge-credit-card
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    platform.banking.io/layer: edge
spec:
  project: banking-staging
  destination:
    server: https://kubernetes.default.svc
    namespace: banking
  source:
    repoURL: https://github.com/LeDangQuocAn/banking-gitops.git
    targetRevision: master
    path: charts/banking-spring-boot
    helm:
      releaseName: credit-card-staging
      valueFiles:
        - ../../environments/staging/credit-card-values.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
