{{- if and .Values.secret.enabled .Values.secret.existingSecret }}
{{- fail "secret.enabled and secret.existingSecret are mutually exclusive" -}}
{{- end }}
{{- if .Values.secret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "banking-spring-boot.fullname" . }}
  labels:
    {{- include "banking-spring-boot.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if not .Values.secret.stringData }}
  {}
  {{- else }}
  {{- range $key, $value := .Values.secret.stringData }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- end }}
{{- end }}
