namespace: banking

clusterSecretStore:
  enabled: false
  name: vault-backend
  provider: vault
  vault:
    server: http://vault.vault.svc.cluster.local:8200
    path: banking
    version: v2
    auth:
      mountPath: kubernetes
      role: external-secrets
      serviceAccountRef:
        name: external-secrets
        namespace: external-secrets
  aws:
    region: ap-southeast-1
    auth:
      serviceAccountRef:
        name: external-secrets
        namespace: external-secrets

externalSecrets:
  secretStore:
    name: vault-backend
    kind: ClusterSecretStore
  refreshInterval: 1h
  rdsCredentials:
    enabled: false
    name: staging-rds-external-secret
    targetName: staging-rds-credentials
    vaultPath: banking/rds
  elasticacheCredentials:
    enabled: false
    name: staging-elasticache-external-secret
    targetName: staging-elasticache-credentials
    authToken: ""
    vaultPath: banking/redis
  rabbitmqCredentials:
    enabled: false
    name: staging-rabbitmq-external-secret
    targetName: infra-staging-rabbitmq
    vaultPath: banking/rabbitmq
  mqCredentials:
    enabled: false
    name: prod-mq-external-secret
    targetName: banking-prod-mq-secret
    targetNamespace: banking-prod
    secretName: Banking-Microservices-Prod-amazon-mq-credentials
  docdbCredentials:
    enabled: false
    name: prod-docdb-external-secret
    targetName: banking-prod-docdb-secret
    vaultPath: banking/docdb
  slackWebhook:
    enabled: false
    name: prod-slack-webhook-external-secret
    targetName: prod-slack-webhook
    targetNamespace: monitoring
    vaultPath: banking/slack
