apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: staging-core-shared-secrets
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
    platform.banking.io/layer: core
    platform.banking.io/priority: foundational
spec:
  project: banking-staging
  destination:
    server: https://kubernetes.default.svc
    namespace: banking
  source:
    repoURL: https://github.com/LeDangQuocAn/banking-gitops.git
    targetRevision: master
    path: charts/shared-secrets
    helm:
      releaseName: shared-secrets-staging
      valueFiles:
        - ../../environments/staging/shared-secrets-values.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
