{{- if .Values.clusterSecretStore.enabled }}
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: {{ .Values.clusterSecretStore.name }}
spec:
  provider:
    {{- if eq (.Values.clusterSecretStore.provider | default "vault") "aws" }}
    aws:
      service: SecretsManager
      region: {{ .Values.clusterSecretStore.aws.region | quote }}
      auth:
        jwt:
          serviceAccountRef:
            name: {{ .Values.clusterSecretStore.aws.auth.serviceAccountRef.name | quote }}
            namespace: {{ .Values.clusterSecretStore.aws.auth.serviceAccountRef.namespace | quote }}
    {{- else }}
    vault:
      server: {{ .Values.clusterSecretStore.vault.server | quote }}
      path: {{ .Values.clusterSecretStore.vault.path | quote }}
      version: {{ .Values.clusterSecretStore.vault.version | quote }}
      auth:
        kubernetes:
          mountPath: {{ .Values.clusterSecretStore.vault.auth.mountPath | quote }}
          role: {{ .Values.clusterSecretStore.vault.auth.role | quote }}
          serviceAccountRef:
            name: {{ .Values.clusterSecretStore.vault.auth.serviceAccountRef.name | quote }}
            namespace: {{ .Values.clusterSecretStore.vault.auth.serviceAccountRef.namespace | quote }}
    {{- end }}
{{- end }}
