apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: banking-staging-controllers-aws-load-balancer-controller
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: banking-platform
    app.kubernetes.io/managed-by: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
    platform.banking.io/environment: staging
    platform.banking.io/layer: controllers
spec:
  project: banking-staging
  
  source:
    repoURL: https://aws.github.io/eks-charts
    chart: aws-load-balancer-controller
    targetRevision: 2.6.2
    helm:
      releaseName: aws-load-balancer-controller
      values: |
        clusterName: banking-staging
        replicaCount: 1
        serviceAccount:
          create: false
          name: aws-load-balancer-controller
          annotations:
            eks.amazonaws.com/role-arn: arn:aws:iam::141571819416:role/banking-microservices-staging-alb-controller-role
        enableWaf: false
        enableWafv2: false
        image:
          tag: v2.6.2
  
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=false
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m

